import {
  Users,
  ShieldCheck,
  FileSpreadsheet,
  BookOpen,
  Video,
  Clapperboard,
  CalendarDays,
  FolderOpen,
  ListChecks,
  ClipboardCheck,
  ClipboardList,
  GraduationCap,
  UploadCloud,
  UserSearch,
  QrCode,
  Award,
  BarChart3,
  CreditCard,
  Eye,
} from "lucide-react";
import type { Article } from "../types";

export const TEAM_ARTICLES: Article[] = [
  {
    slug: "usuarios",
    audience: "team",
    category: "Personas",
    icon: Users,
    title: "Usuarios y matrículas",
    summary: "Crea cuentas, asigna roles y matricula alumnos.",
    overview:
      "El panel de Usuarios centraliza todas las cuentas. Creas usuarios, los filtras, los asignas a cohortes con un rol y gestionas sus invitaciones.",
    steps: [
      "Crea usuarios uno por uno con “Nuevo usuario” o en masa con “Importar CSV”.",
      "Filtra por entorno (programa), por estado (activos/pendientes) y por rol.",
      "Usa el menú de cada usuario para ver su perfil, editarlo, asignarlo a una cohorte o desactivarlo.",
      "Reenvía la invitación a quienes aún no activan su cuenta.",
      "Marca alumnos “Capital Inteligente” para mostrarles clases exclusivas de ese segmento.",
    ],
    tips: ["Solo un Administrador puede crear o ascender cuentas a Ops/Admin; un Ops gestiona alumnos."],
    faqs: [
      {
        q: "¿Qué diferencia hay entre desactivar y eliminar?",
        a: "Desactivar bloquea el acceso y cierra las sesiones, pero conserva los datos para poder reactivar. No hay borrado destructivo.",
      },
    ],
    route: () => "/admin/users",
    routeLabel: "Ir a Usuarios",
  },
  {
    slug: "roles",
    audience: "team",
    category: "Personas",
    icon: ShieldCheck,
    title: "Roles y permisos",
    summary: "Quién puede hacer qué, a nivel plataforma y por cohorte.",
    overview:
      "Hay dos niveles de rol. El rol de plataforma define el acceso al panel; el rol por cohorte define qué hace dentro de un programa.",
    steps: [
      "Rol de plataforma: Administrador (todo), Ops (gestión sin tocar otros admins) y Usuario (solo su classroom).",
      "Rol por cohorte: Alumno (ve contenido y rinde), Profesor (imparte y gestiona sus módulos) y Ayudante (apoya al profesor).",
      "Un alumno siempre tiene una matrícula asociada a su cohorte.",
    ],
    tips: [
      "Ser Administrador de plataforma no te da acceso a una cohorte donde no tienes rol; el staff sí puede entrar a cualquier classroom para revisar.",
    ],
    route: () => "/admin/users",
    routeLabel: "Ir a Usuarios",
  },
  {
    slug: "importar-csv",
    audience: "team",
    category: "Personas",
    icon: FileSpreadsheet,
    title: "Importar usuarios por CSV",
    summary: "Carga muchos alumnos de una vez.",
    overview:
      "La importación masiva crea (o asigna) varios usuarios a la vez desde un archivo, y opcionalmente les envía la invitación.",
    steps: [
      "En Usuarios, abre “Importar CSV” y descarga la plantilla.",
      "Completa: nombre, email, teléfono y RUT (los dos primeros son obligatorios).",
      "Sube el archivo y revisa la vista previa: marca duplicados y filas con error.",
      "Elige la cohorte de destino y si quieres enviar invitaciones.",
      "Confirma; al final ves un resumen de creados, asignados y omitidos.",
    ],
    tips: [
      "Hasta ~50 filas por carga. Si un email ya existe, se asigna a la cohorte sin duplicar la cuenta.",
    ],
    route: () => "/admin/users",
    routeLabel: "Ir a Usuarios",
  },
  {
    slug: "contenido",
    audience: "team",
    category: "Contenido",
    icon: BookOpen,
    title: "Módulos y lecciones",
    summary: "Estructura el programa y ordena su contenido.",
    overview:
      "Aquí construyes la estructura de cada programa: módulos que contienen lecciones grabadas, más las clases en vivo de la cohorte.",
    steps: [
      "Elige el programa y la cohorte (la cohorte filtra las clases en vivo).",
      "Crea módulos y, dentro, lecciones grabadas.",
      "Reordena lecciones con las flechas y muévelas entre módulos del mismo programa.",
      "Usa “apertura por calendario” para que una lección se desbloquee en una fecha.",
    ],
    tips: ["No se puede eliminar una lección o módulo con progreso de alumnos o clases vinculadas; la plataforma te avisa."],
    route: () => "/admin/lessons",
    routeLabel: "Ir a Lecciones",
  },
  {
    slug: "video",
    audience: "team",
    category: "Contenido",
    icon: Video,
    title: "Video o contenido de la clase",
    summary: "Una clase puede ser de video o de texto/diapositiva.",
    overview:
      "Una lección no tiene que ser de video. Puede ser una clase de texto: una explicación con formato (títulos, listas, imágenes intercaladas) que el alumno lee. Así una clase puede ser un video, un contenido escrito, o ambos con su material.",
    steps: [
      "Entra al editor de la lección con “Editar”.",
      "Para video: arrastra el archivo (MP4, MOV o WebM, hasta 12 GB) y espera el procesamiento.",
      "Para una clase de texto: escribe en “Contenido de la clase” usando Markdown; con “Insertar imagen” intercalas diapositivas o capturas. La pestaña “Vista previa” muestra cómo lo verá el alumno.",
      "Si la lección no tiene video, el alumno ve el contenido escrito y su material, con un botón para marcarla como completada.",
    ],
    tips: ["Una clase puede combinar video y contenido escrito; ambos son opcionales."],
    route: () => "/admin/lessons",
    routeLabel: "Ir a Lecciones",
  },
  {
    slug: "calendario-admin",
    audience: "team",
    category: "Contenido",
    icon: CalendarDays,
    title: "Calendario y clases en vivo",
    summary: "Agenda clases en vivo y carga su material.",
    overview:
      "Las clases en vivo viven en el calendario de cada cohorte. Defines fecha, profesor, modalidad y el material que verá el alumno.",
    steps: [
      "Crea o edita una sesión: título, inicio/fin, modalidad, instructor, link de reunión y módulo.",
      "Elige la audiencia: toda la cohorte o solo el segmento “Capital Inteligente”.",
      "Adjunta el “Material de la clase” (archivos o enlaces).",
      "La plataforma envía recordatorios automáticos antes de cada clase.",
    ],
    tips: ["Una clase solo puede vincularse a un módulo de su propio programa."],
    route: (ctx) => (ctx.adminCohortId ? `/admin/cohorts/${ctx.adminCohortId}/sesiones` : null),
    routeLabel: "Ir al calendario",
  },
  {
    slug: "grabar-repeticion",
    audience: "team",
    category: "Contenido",
    icon: Clapperboard,
    title: "Grabar una clase en vivo y publicar su repetición",
    summary: "Quién graba, cómo se sube el archivo y qué hace sola la plataforma.",
    overview:
      "La repetición de una clase en vivo no se genera sola: alguien graba la pantalla de su computador mientras la clase ocurre y ese archivo se sube a la clase en el calendario de la cohorte. Desde la subida en adelante la plataforma hace el resto: procesa el video, lo transcribe, arma resumen y capítulos, y avisa por correo a los alumnos de la cohorte.",
    steps: [
      "Antes de la clase, acuerda quién graba (el profesor o alguien del equipo que la acompañe) y confirma que grabará la pantalla completa con el audio del computador y el micrófono.",
      "Se graba con lo que ya trae el computador: en Mac, Shift + Command + 5; en Windows, la barra de juego (tecla Windows + G). OBS Studio también sirve si esa persona ya lo usa.",
      "Revisa que la clase tenga un módulo asignado. Sin módulo no se puede crear la repetición y el panel lo dice explícitamente.",
      "Con el archivo en mano, abre el calendario de la cohorte, ubica la clase en la lista de “Pasadas” y usa el botón “Subir grabación”: abre la edición de esa clase con el panel “Repetición de la clase” a la vista.",
      "Si es la primera vez, haz clic en “Preparar y subir repetición”; después arrastra el archivo (MP4, MOV o WebM, hasta 12 GB).",
      "Espera. El panel muestra “Procesando en Mux…” y se actualiza solo: no necesitas refrescar ni quedarte mirando.",
      "Cuando aparece “Repetición lista”, el alumno ya la ve en la pantalla de esa clase —con transcripción, resumen y capítulos generados automáticamente— y recibe el correo de grabación disponible.",
    ],
    tips: [
      "El botón “Subir grabación” aparece solo en las clases que ya ocurrieron y todavía no tienen repetición publicada; cuando el video queda listo, desaparece de la fila.",
      "La repetición queda enlazada a la clase, no como una lección suelta del módulo: no la busques en el listado de Lecciones.",
      "Si Mux falla al procesar, el panel muestra el motivo y ofrece reintentar la subida sin rehacer nada más.",
      "“Quitar repetición” borra el video de esa clase: úsalo si subiste el archivo equivocado y vuelve a subir el correcto.",
      "La sala tiene grabación automática (parte sola cuando entra el docente y la repetición se publica sin subir nada), pero depende de que el servicio de grabación esté habilitado en la plataforma. Mientras no lo esté, la repetición se sube a mano como describe esta guía. Cuando una clase se grabó sola, el panel lo avisa: no subas un archivo encima.",
    ],
    faqs: [
      {
        q: "¿Puedo subir la repetición desde Lecciones?",
        a: "Para una clase en vivo, no. Se sube desde el calendario de la cohorte, en la clase que corresponde: así queda enlazada a esa clase y el alumno la encuentra donde la espera.",
      },
      {
        q: "El panel dice que asigne un módulo a la sesión.",
        a: "La repetición se crea como una clase grabada dentro de un módulo del programa. Edita la clase, elige su módulo, guarda y vuelve a intentar.",
      },
      {
        q: "El video lleva mucho rato “Procesando”.",
        a: "El procesamiento normal toma unos minutos. Si se pasa, el panel te deja volver a consultar el estado; el proceso sigue corriendo igual y se marca listo cuando termina.",
      },
      {
        q: "Nadie grabó la clase. ¿Se puede recuperar?",
        a: "No. La sala transmite pero no graba, así que si nadie grabó su pantalla no queda archivo. Por eso conviene definir a la persona que graba antes de cada clase.",
      },
    ],
    route: (ctx) => (ctx.adminCohortId ? `/admin/cohorts/${ctx.adminCohortId}/sesiones` : null),
    routeLabel: "Ir al calendario",
  },
  {
    slug: "recursos-admin",
    audience: "team",
    category: "Contenido",
    icon: FolderOpen,
    title: "Recursos y materiales",
    summary: "Sube PDFs, plantillas y enlaces, todo desde Lecciones.",
    overview:
      "La gestión de material se hace en un solo lugar: el editor de Lecciones. Tanto las lecciones grabadas como las clases en vivo del calendario adjuntan ahí su material, y el alumno lo descarga con un enlace seguro y temporal.",
    steps: [
      "Entra a “Lecciones” y elige el programa (y la cohorte para las clases en vivo).",
      "Para una lección grabada: abre su editor con “Editar” y agrega un archivo (hasta 50 MB) o un enlace.",
      "Para una clase en vivo: abre su panel “Material” (botón en la fila) y sube el archivo o enlace ahí mismo, sin salir a otra pantalla.",
    ],
    tips: [
      "Acepta cualquier tipo de archivo. Los enlaces solo admiten http/https por seguridad.",
      "La antigua página “Recursos por lección” ahora redirige a Lecciones: todo se gestiona desde un mismo lugar.",
    ],
    route: () => "/admin/lessons",
    routeLabel: "Ir a Lecciones",
  },
  {
    slug: "evaluaciones",
    audience: "team",
    category: "Evaluación",
    icon: ClipboardList,
    title: "Evaluaciones: la sección",
    summary: "Crea y organiza todas las evaluaciones del programa desde un solo lugar.",
    overview:
      "La evaluación es la entidad; el quiz es solo uno de sus dos tipos. Cada evaluación tiene un tipo (quiz autocorregido o nota manual) y un alcance (examen final, módulo, lección o clase en vivo). La lista las agrupa por módulo y te muestra la suma de pesos de cada grupo.",
    steps: [
      "Entra a “Evaluaciones” y elige “+ Nueva evaluación”.",
      "Elige el tipo: Quiz (se autocorrige) o Nota manual (la calificas tú, por ejemplo un roleplay o un guión de venta).",
      "Elige el alcance —final del programa, de un módulo, de una lección o de una clase en vivo— y selecciona el módulo, la lección o la clase que corresponda.",
      "Escribe el título (te sugiere uno automático que puedes editar) y confirma: entras directo a configurarla.",
    ],
    tips: [
      "El tipo y el alcance no se pueden cambiar después de crear la evaluación: elígelos bien la primera vez.",
      "La evaluación final debe ser un quiz: es la única que emite certificado.",
      "Un módulo admite varias notas manuales, pero solo un quiz.",
    ],
    faqs: [
      {
        q: "¿Puedo crear una evaluación sin pasar por una lección o una clase?",
        a: "Sí. “+ Nueva evaluación” crea cualquier tipo y alcance directo desde esta sección, sin que tengas que entrar antes a Lecciones o al calendario.",
      },
    ],
    route: () => "/admin/evaluaciones",
    routeLabel: "Ir a Evaluaciones",
  },
  {
    slug: "quizzes-clase",
    audience: "team",
    category: "Evaluación",
    icon: ListChecks,
    title: "Quizzes por clase",
    summary: "Evaluaciones formativas dentro de cada lección o clase en vivo.",
    overview:
      "Crea quizzes dentro de una lección o de una clase en vivo. No certifican ni bloquean el avance del alumno, pero sí generan una nota 1-7 que se publica sola y que el alumno ve en su pantalla de Notas: si le pones peso, esa nota entra al promedio del módulo.",
    steps: [
      "En el editor de una lección, baja a “Evaluación de la clase” y créala; para una clase en vivo, ábrela desde “Evaluación de la clase” en el panel de la sesión.",
      "También puedes crearla directo desde “Evaluaciones” con “+ Nueva evaluación”, eligiendo el alcance “De la lección” o “De la clase en vivo”.",
      "Agrega preguntas de cualquiera de los 4 tipos: opción única, opción múltiple, verdadero/falso o respuesta corta.",
      "Si quieres que su nota pese en el promedio del módulo, ponle un peso en Ajustes.",
      "Actívala para que el alumno la vea (requiere al menos una pregunta).",
    ],
    tips: [
      "La respuesta corta se corrige ignorando mayúsculas, tildes y espacios.",
      "La opción múltiple exige marcar exactamente las respuestas correctas (sin puntaje parcial).",
      "Ojo con el peso: si lo defines, esta nota deja de ser “solo práctica” para el promedio del alumno, aunque nunca certifique el programa.",
    ],
    route: () => "/admin/lessons",
    routeLabel: "Ir a Lecciones",
  },
  {
    slug: "examen-final-admin",
    audience: "team",
    category: "Evaluación",
    icon: ClipboardCheck,
    title: "Examen final y configuración",
    summary: "Configura el examen que certifica el programa.",
    overview:
      "El examen final es el que emite certificado. Defines sus reglas, cargas el pool de preguntas y revisas los intentos de los alumnos.",
    steps: [
      "En “Evaluaciones”, abre la evaluación final y ajusta sus Ajustes: completitud mínima, nota de aprobación, intentos y, si quieres, una ventana de apertura y cierre.",
      "Carga las preguntas manualmente o genéralas con IA a partir del contenido del programa.",
      "Activa el examen y revisa los intentos de los alumnos en la pestaña “Respuestas”.",
    ],
    tips: [
      "Las preguntas de opción única admiten hasta 6 alternativas (A a F).",
      "Si defines una fecha de cierre, un alumno que ya empezó su intento igual puede entregarlo aunque la ventana ya haya cerrado.",
      "La nota del examen se sincroniza sola a la pantalla de Notas; no necesitas cargarla a mano.",
    ],
    faqs: [
      {
        q: "¿Puedo poner preguntas de verdadero/falso en el examen final?",
        a: "Sí, puedes agregar a mano cualquiera de los 4 tipos. Lo único fijo es que la generación con IA arma siempre preguntas de opción única.",
      },
    ],
    route: () => "/admin/evaluaciones",
    routeLabel: "Ir a Evaluaciones",
  },
  {
    slug: "notas-admin",
    audience: "team",
    category: "Evaluación",
    icon: GraduationCap,
    title: "Cargar y publicar notas 1-7",
    summary: "Califica a cada alumno, arma tu checklist y decide cuándo la ve.",
    overview:
      "La pestaña “Notas” de cada evaluación es donde calificas: escala 1-7, comentario, checklist de criterios propio y control de publicación. También puedes cargar muchas notas de una vez desde un Excel.",
    steps: [
      "Entra a la evaluación y abre su pestaña “Notas”.",
      "Si el programa tiene más de una cohorte, elige la cohorte para ver su roster.",
      "Escribe la nota (1-7) y, si quieres, un comentario; marca el checklist de criterios que hayas definido.",
      "Guarda como borrador (solo tú lo ves) o “Guardar y publicar” (el alumno la ve de inmediato en su pantalla de Notas).",
      "Para cargar muchas notas de una vez, usa “Importar Excel”: sube el archivo, revisa la vista previa y confirma.",
    ],
    tips: [
      "“Publicar todas” publica de una vez todas las notas pendientes de la cohorte.",
      "Despublicar retira la nota de la vista del alumno; úsalo solo si te equivocaste.",
      "Si la evaluación es un quiz autocorregido, su nota ya llega marcada “Auto (quiz)” y publicada; si la editas y guardas a mano, pasa a quedar como tu nota manual.",
    ],
    faqs: [
      {
        q: "¿Qué pasa si guardo una nota manual sobre una que puso el quiz solo?",
        a: "La reemplaza: queda tu nota, marcada como manual, en vez de la que generó el quiz.",
      },
    ],
    route: () => "/admin/evaluaciones",
    routeLabel: "Ir a Evaluaciones",
  },
  {
    slug: "certificacion",
    audience: "team",
    category: "Evaluación",
    icon: Award,
    title: "Certificación",
    summary: "Emisión y verificación de certificados.",
    overview:
      "El certificado se emite automáticamente cuando un alumno aprueba el examen final. Es verificable públicamente y único por matrícula. Vive en su propia sección, separada de Evaluaciones.",
    steps: [
      "Entra a “Certificados” y revisa los emitidos por programa.",
      "Si necesitas emitir uno a mano, usa el formulario con la matrícula del alumno: es una excepción deliberada, pensada para casos puntuales.",
      "Cualquiera puede verificar un certificado con su código en /verificar.",
    ],
    tips: [
      "Solo el examen final emite certificado automático; una nota alta en un quiz de clase no lo habilita por sí sola, aunque tenga peso en el promedio.",
      "La emisión manual no exige que exista un intento del examen: úsala con criterio, es un override deliberado para excepciones.",
    ],
    route: () => "/admin/certificados",
    routeLabel: "Ir a Certificados",
  },
  {
    slug: "progreso",
    audience: "team",
    category: "Operación",
    icon: BarChart3,
    title: "Progreso de la cohorte",
    summary: "Mira el avance de cada alumno y detecta riesgo.",
    overview:
      "El reporte de progreso muestra cuánto ha avanzado cada alumno, por módulo, para que identifiques a quienes necesitan acompañamiento.",
    steps: [
      "Elige la cohorte.",
      "Revisa el promedio, quiénes completaron y quiénes van atrasados (menos de 30%).",
      "Haz clic en un alumno para ver su detalle por módulo.",
    ],
    route: () => "/admin/progress",
    routeLabel: "Ir a Progreso",
  },
  {
    slug: "alumnos-admin",
    audience: "team",
    category: "Operación",
    icon: UserSearch,
    title: "Ficha del alumno",
    summary: "Busca a un alumno y ve todo su historial en un solo lugar.",
    overview:
      "El panel de Alumnos junta en una sola ficha lo que hoy tienes repartido en otras pantallas: asistencia, avance y evaluaciones de un alumno puntual, filtrable por cohorte.",
    steps: [
      "Filtra por cohorte si el programa tiene más de una.",
      "Busca al alumno por nombre o email, o usa los filtros “En riesgo” y “Atrasados”.",
      "Haz clic en su fila para abrir la ficha: asistencia, avance y evaluaciones aprobadas/pendientes.",
      "Dentro de la ficha revisa qué sesiones se perdió, qué lecciones le faltan y qué evaluaciones tiene pendientes.",
    ],
    tips: [
      "“En riesgo” marca a quien acumula 2 o más inasistencias; “Atrasados”, a quien va bajo el 30% de avance.",
    ],
    route: () => "/admin/alumnos",
    routeLabel: "Ir a Alumnos",
  },
  {
    slug: "entregables-admin",
    audience: "team",
    category: "Operación",
    icon: UploadCloud,
    title: "Entregables",
    summary: "Crea tareas con fecha límite y revisa quién ya entregó.",
    overview:
      "Un entregable es una tarea con ventana de entrega (apertura y fecha límite) y tipos de archivo permitidos. El alumno sube su archivo desde el classroom y tú revisas quién ya entregó, desde aquí.",
    steps: [
      "Elige el programa y haz clic en “Nuevo entregable”.",
      "Define título, descripción, fecha de apertura y fecha límite.",
      "Elige los tipos de archivo permitidos y el tamaño máximo, y si el alumno puede subir varios archivos o solo uno (el último reemplaza al anterior).",
      "Guarda; el entregable aparece en el classroom del alumno en cuanto se abre su ventana.",
      "Usa el ícono de personas de cada entregable para ver quién ya entregó y descargar sus archivos.",
    ],
    tips: [
      "Si “Permitir varios archivos” está desactivado, una nueva entrega reemplaza a la anterior; si está activado, se suman.",
      "Eliminar un entregable borra también las entregas de los alumnos.",
    ],
    route: () => "/admin/deliverables",
    routeLabel: "Ir a Entregables",
  },
  {
    slug: "asistencia-admin",
    audience: "team",
    category: "Operación",
    icon: QrCode,
    title: "Asistencia y QR",
    summary: "Genera el QR de una clase y corrige la lista a mano.",
    overview:
      "Cada clase en vivo tiene su propio código QR de asistencia y su reporte de quién marcó presente. También puedes corregir la lista a mano cuando alguien no alcanzó a escanear.",
    steps: [
      "En el calendario de la cohorte, abre la clase y usa el botón “QR” para mostrarlo, imprimirlo o copiar el enlace.",
      "El alumno escanea el QR (o abre el enlace) y queda marcado presente en esa clase.",
      "Usa el botón “Asistencia” para ver el reporte de presentes y marcar o desmarcar a mano a quien lo necesite.",
    ],
    tips: [
      "El QR apunta a una página pública de check-in por sesión: cualquiera con el enlace puede marcarse, así que compártelo solo en la clase.",
      "Si el programa tiene la alerta de inasistencias activada, la plataforma avisa por correo cuando un alumno acumula el número de faltas definido para ese programa.",
    ],
    route: (ctx) => (ctx.adminCohortId ? `/admin/cohorts/${ctx.adminCohortId}/sesiones` : null),
    routeLabel: "Ir al calendario",
  },
  {
    slug: "cobros",
    audience: "team",
    category: "Operación",
    icon: CreditCard,
    title: "Cobros y pagos",
    summary: "Genera enlaces de cobro para montos puntuales.",
    overview:
      "Crea un enlace de cobro firmado para un monto específico y compártelo. El cliente paga al contado o en cuotas, con el recargo calculado automáticamente.",
    steps: [
      "Define el monto y el concepto.",
      "Genera el enlace y compártelo por correo o WhatsApp.",
      "El cliente elige contado, 6 o 12 cuotas y paga por Flow.",
    ],
    tips: ["El monto va firmado: el cliente no puede alterarlo desde el enlace."],
    route: () => "/admin/cobros",
    routeLabel: "Ir a Cobros",
  },
  {
    slug: "entornos-vista",
    audience: "team",
    category: "Operación",
    icon: Eye,
    title: "Entorno activo y “Ver como”",
    summary: "Enfoca el panel a un programa y revisa la vista del alumno.",
    overview:
      "Arriba del menú tienes dos controles de staff. El selector de “Entorno” enfoca el panel a un programa (Diplomado, Workshop, Liderazgo), y el interruptor “Ver como: Admin / Alumno” te deja revisar la experiencia del estudiante sin perder tu acceso de administrador.",
    steps: [
      "Elige el “Entorno” para que Usuarios, Progreso y Quizzes muestren solo ese programa.",
      "Cambia a “Alumno” para recorrer el classroom como lo ve un estudiante; vuelve con “Admin”.",
      "Es un cambio de VISTA, no de permisos: tu rol y lo que puedes hacer no cambian.",
    ],
    tips: [
      "Estando en el panel (/admin) siempre ves la navegación de administrador, aunque hayas dejado activado “Ver como alumno”.",
    ],
  },
];
